In [267]:
import pandas as pd
import numpy as np
import requests

In [268]:
url='https://api.themoviedb.org/3/movie/top_rated?api_key=8265bd1679663a7ea12ac168da84d2e8&language=en-US&page={}'

In [269]:
df=[]

In [270]:
for idx in range(1,500):
  responce=requests.get(url.format(idx))
  data=responce.json()
  for movie in data["results"]:
    df.append({'movie_name':movie['title'],'summary':movie['overview']})

In [271]:
df=pd.DataFrame(df)

In [272]:
df.head(20)

,movie_name,summary
0,Avatar Aang: The Last Airbender,"Avatar Aang, the world's last Airbender, learn..."
1,Accidental Partners,Two women discover they were both scammed by t...
2,Swapped,"A small woodland creature and a majestic bird,..."
3,Facing El Chapo,Two Mexican officers must survive the final ho...
4,Demon Slayer: Kimetsu no Yaiba Infinity Castle,The Demon Slayer Corps are drawn into the Infi...
5,The Shawshank Redemption,Imprisoned in the 1940s for the double murder ...
6,The Godfather,"Spanning the years 1945 to 1955, a chronicle o..."
7,Michael,"The story of Michael Jackson, one of the most ..."
8,Project Hail Mary,Science teacher Ryland Grace wakes up on a spa...
9,The Godfather Part II,In the continuing saga of the Corleone crime f...
10,12 Angry Men,The defense and the prosecution have rested an...
11,Schindler's List,The true story of how businessman Oskar Schind...
12,Young Hearts,14-year-old Elias increasingly feels like an o...
13,The Dark Knight,Batman raises the stakes in his war on crime. ...
14,Spirited Away,"A young girl, Chihiro, becomes trapped in a st..."
15,Chainsaw Man - The Movie: Reze Arc,"In a brutal war between devils, hunters, and s..."
16,The Green Mile,A supernatural tale set on death row in a Sout...
17,The Lord of the Rings: The Return of the King,As armies mass for a final battle that will de...
18,Dilwale Dulhania Le Jayenge,"Raj is a rich, carefree, happy-go-lucky second..."
19,Parasite,"All unemployed, Ki-taek's family takes peculia..."

# Text Preprocessing

**To lower case**

In [273]:
df['summary']=df['summary'].str.lower()
df['movie_name']=df['movie_name'].str.lower()

In [274]:
df['summary'].head()

0    avatar aang, the world's last airbender, learn...
1    two women discover they were both scammed by t...
2    a small woodland creature and a majestic bird,...
3    two mexican officers must survive the final ho...
4    the demon slayer corps are drawn into the infi...
Name: summary, dtype: object

In [275]:
df.head()

,movie_name,summary
0,avatar aang: the last airbender,"avatar aang, the world's last airbender, learn..."
1,accidental partners,two women discover they were both scammed by t...
2,swapped,"a small woodland creature and a majestic bird,..."
3,facing el chapo,two mexican officers must survive the final ho...
4,demon slayer: kimetsu no yaiba infinity castle,the demon slayer corps are drawn into the infi...

In [276]:
df.iloc[0]['summary']

"avatar aang, the world's last airbender, learns of an ancient power that could save his culture from extinction. with the help of his friends, he embarks on a global quest to find it before it falls into the wrong hands and threatens to upend the peace they sacrificed everything to achieve."

**Removing HTML Tags**

In [277]:
df.loc[0, 'summary'] = "A <b>young</b> man enters a <i>strange</i> world."

In [278]:
df.iloc[0]['summary']

'A <b>young</b> man enters a <i>strange</i> world.'

In [279]:
import re
def remove_html(text):
  pattern=re.compile('<.*?>')
  return pattern.sub('',text)
df['summary']=df['summary'].apply(remove_html)

In [280]:
df.loc[0,'summary']

'A young man enters a strange world.'

In [281]:
df.loc[0, 'summary']=temp

In [282]:
df.head()

,movie_name,summary
0,avatar aang: the last airbender,"avatar aang, the world's last airbender, learn..."
1,accidental partners,two women discover they were both scammed by t...
2,swapped,"a small woodland creature and a majestic bird,..."
3,facing el chapo,two mexican officers must survive the final ho...
4,demon slayer: kimetsu no yaiba infinity castle,the demon slayer corps are drawn into the infi...

**Removing Punctauations**

In [283]:
df.iloc[976]['summary']

'law enforcement officers adam mitchell, nathan hayes, and their partners stand up to the worst the streets have to offer with confidence and focus. yet at the end of the day, they face a challenge that none of them are truly prepared to tackle: fatherhood. they know that god desires to turn the hearts of fathers to their children, but their children are beginning to drift further and further away from them. when tragedy hits home, these men are left wrestling with their hopes, their fears, their faith, and their fathering. can a newfound urgency help these dads draw closer to god... and to their children?'

In [284]:
import string
punc=string.punctuation
df['summary']=df['summary'].apply(lambda x:x.translate(str.maketrans('', '', punc)))
df['movie_name']=df['movie_name'].apply(lambda x:x.translate(str.maketrans('', '', punc)))

In [285]:
df.iloc[976]['summary']

'law enforcement officers adam mitchell nathan hayes and their partners stand up to the worst the streets have to offer with confidence and focus yet at the end of the day they face a challenge that none of them are truly prepared to tackle fatherhood they know that god desires to turn the hearts of fathers to their children but their children are beginning to drift further and further away from them when tragedy hits home these men are left wrestling with their hopes their fears their faith and their fathering can a newfound urgency help these dads draw closer to god and to their children'

In [286]:
df.head()

,movie_name,summary
0,avatar aang the last airbender,avatar aang the worlds last airbender learns o...
1,accidental partners,two women discover they were both scammed by t...
2,swapped,a small woodland creature and a majestic bird ...
3,facing el chapo,two mexican officers must survive the final ho...
4,demon slayer kimetsu no yaiba infinity castle,the demon slayer corps are drawn into the infi...

In [287]:
temp=df.iloc[0]['summary']

**Slang words**

slang words

In [288]:
slang_map = {
    "A3": "Anytime, Anywhere, Anyplace",
    "ADIH": "Another Day In Hell",
    "AFK": "Away From Keyboard",
    "AFAIK": "As Far As I Know",
    "ASAP": "As Soon As Possible",
    "ASL": "Age, Sex, Location",
    "ATK": "At The Keyboard",
    "ATM": "At The Moment",
    "BAE": "Before Anyone Else",
    "BAK": "Back At Keyboard",
    "BBL": "Be Back Later",
    "BBS": "Be Back Soon",
    "BFN": "Bye For Now",
    "B4N": "Bye For Now",
    "BRB": "Be Right Back",
    "BRUH": "Bro",
    "BRT": "Be Right There",
    "BTW": "By The Way",
    "CSL": "Can't Stop Laughing",
    "CU": "See You",
    "CUL8R": "See You Later",
    "CYA": "See You",
    "DM": "Direct Message",
    "FAQ": "Frequently Asked Questions",
    "FC": "Fingers Crossed",
    "FOMO": "Fear Of Missing Out",
    "FR": "For Real",
    "FWIW": "For What It's Worth",
    "FYP": "For You Page",
    "FYI": "For Your Information",
    "GG": "Good Game",
    "GN": "Good Night",
    "GOAT": "Greatest Of All Time",
    "GR8": "Great",
    "HBD": "Happy Birthday",
    "IDC": "I Don't Care",
    "IDK": "I Don't Know",
    "ILU": "I Love You",
    "ILY": "I Love You",
    "IMHO": "In My Honest/Humble Opinion",
    "IMO": "In My Opinion",
    "IOW": "In Other Words",
    "IRL": "In Real Life",
    "IYKYK": "If You Know, You Know",
    "JK": "Just Kidding",
    "L8R": "Later",
    "LMK": "Let Me Know",
    "LMAO": "Laughing My A** Off",
    "LOL": "Laughing Out Loud",
    "LTNS": "Long Time No See",
    "M8": "Mate",
    "MFW": "My Face When",
    "MID": "Mediocre",
    "MRW": "My Reaction When",
    "MTE": "My Thoughts Exactly",
    "NVM": "Never Mind",
    "NPC": "Non-Player Character",
    "OIC": "Oh I See",
    "OP": "Overpowered",
    "PITA": "Pain In The A**",
    "POV": "Point Of View",
    "ROFL": "Rolling On The Floor Laughing",
    "ROFLOL": "Rolling On The Floor Laughing Out Loud",
    "ROTFLMAO": "Rolling On The Floor Laughing My A** Off",
    "RN": "Right Now",
    "SK8": "Skate",
    "SUS": "Suspicious",
    "TBH": "To Be Honest",
    "TFW": "That Feeling When",
    "THX": "Thank You",
    "TLDR": "Too Long, Didn't Read",
    "TNTL": "Trying Not To Laugh",
    "TTYL": "Talk To You Later",
    "U": "You",
    "U2": "You Too",
    "W": "Win",
    "W8": "Wait",
    "WB": "Welcome Back",
    "WTF": "What The F**k",
    "WTG": "Way To Go",
    "WYD": "What You Doing",
    "WYWH": "Wish You Were Here",
    "ZZZ": "Sleeping, Bored, Tired"
}

In [289]:
df.loc[0, 'summary'] = "Tbh the movie has a  sus ending, zzz it was so fun lmao"

In [290]:
import re
def replace_slang(text):
    for slang, meaning in slang_map.items():
        text = re.sub(rf'\b{re.escape(slang)}\b',meaning,text,flags=re.IGNORECASE)
    return text
df['summary'] = df['summary'].apply(replace_slang)

In [291]:
df.iloc[0]['summary']

'To Be Honest the movie has a  Suspicious ending, Sleeping, Bored, Tired it was so fun Laughing My A** Off'

In [292]:
df.loc[0,'summary']=temp

In [293]:
df.head()

,movie_name,summary
0,avatar aang the last airbender,avatar aang the worlds last airbender learns o...
1,accidental partners,two women discover they were both scammed by t...
2,swapped,a small woodland creature and a majestic bird ...
3,facing el chapo,two mexican officers must survive the final ho...
4,demon slayer kimetsu no yaiba infinity castle,the demon slayer corps are drawn into the infi...

**Spelling mistakes**

In [294]:
from textblob import TextBlob

In [295]:
def spelling_correction(text):
  tb=TextBlob(text)
  return tb.correct().string

In [296]:
df.loc[:9, 'movie_name'].apply(spelling_correction)

0                   altar sang the last airbender
1                             accidental partners
2                                         snapped
3                                  facing el chap
4    demon layer kimetsu no labia infinity castle
5                        the shawshank redemption
6                                   the godfather
7                                         michael
8                               project hail mary
9                           the godfather part ii
Name: movie_name, dtype: object

In [297]:
df.head()

,movie_name,summary
0,avatar aang the last airbender,avatar aang the worlds last airbender learns o...
1,accidental partners,two women discover they were both scammed by t...
2,swapped,a small woodland creature and a majestic bird ...
3,facing el chapo,two mexican officers must survive the final ho...
4,demon slayer kimetsu no yaiba infinity castle,the demon slayer corps are drawn into the infi...

**Removing stop words**

In [298]:
import nltk
nltk.download('stopwords')
from nltk.corpus import stopwords
stop_words=set(stopwords.words('english'))

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

In [299]:
df_temp=df

In [300]:
df.head()

,movie_name,summary
0,avatar aang the last airbender,avatar aang the worlds last airbender learns o...
1,accidental partners,two women discover they were both scammed by t...
2,swapped,a small woodland creature and a majestic bird ...
3,facing el chapo,two mexican officers must survive the final ho...
4,demon slayer kimetsu no yaiba infinity castle,the demon slayer corps are drawn into the infi...

In [301]:
def remove_stopwords(text):
    words = text.split()
    rem_words = [word for word in words if word.lower() not in stop_words]
    return ' '.join(rem_words)

In [302]:
df['summary']=df['summary'].apply(remove_stopwords)

In [303]:
df.head()

,movie_name,summary
0,avatar aang the last airbender,avatar aang worlds last airbender learns ancie...
1,accidental partners,two women discover scammed man also got pregna...
2,swapped,small woodland creature majestic bird two natu...
3,facing el chapo,two mexican officers must survive final hours ...
4,demon slayer kimetsu no yaiba infinity castle,demon slayer corps drawn infinity castle tanji...

**demojize**

In [304]:
df.loc[0, 'summary'] = "Amazing movie! 😍🔥 The story was really interesting and the characters were fantastic. 🎬❤️ I loved every moment of it! 😂👏 Definitely worth watching! ⭐⭐⭐⭐⭐"

In [305]:
df.iloc[0]['summary']

'Amazing movie! 😍🔥 The story was really interesting and the characters were fantastic. 🎬❤️ I loved every moment of it! 😂👏 Definitely worth watching! ⭐⭐⭐⭐⭐'

In [306]:
!pip install emoji

Requirement already satisfied: emoji in /usr/local/lib/python3.13/dist-packages (2.15.0)

In [307]:
import emoji
df['summary']=df['summary'].apply(emoji.demojize)

In [308]:
df.iloc[0]['summary']

'Amazing movie! :smiling_face_with_heart-eyes::fire: The story was really interesting and the characters were fantastic. :clapper_board::red_heart: I loved every moment of it! :face_with_tears_of_joy::clapping_hands: Definitely worth watching! :star::star::star::star::star:'

In [309]:
df.loc[0,'summary']=temp

In [310]:
df.head()

,movie_name,summary
0,avatar aang the last airbender,avatar aang the worlds last airbender learns o...
1,accidental partners,two women discover scammed man also got pregna...
2,swapped,small woodland creature majestic bird two natu...
3,facing el chapo,two mexican officers must survive final hours ...
4,demon slayer kimetsu no yaiba infinity castle,demon slayer corps drawn infinity castle tanji...

# Tokenization

In [311]:
import spacy

In [312]:
tok=spacy.load('en_core_web_sm')
def tokenization(sentence):
  doc=tok(sentence)
  return [token.text for token in doc]

In [313]:
df['summary_tokens']=df['summary'].apply(tokenization)

*It does both tokenization or lemmatization*

In [314]:
df.head()

,movie_name,summary,summary_tokens
0,avatar aang the last airbender,avatar aang the worlds last airbender learns o...,"[avatar, aang, the, worlds, last, airbender, l..."
1,accidental partners,two women discover scammed man also got pregna...,"[two, women, discover, scammed, man, also, got..."
2,swapped,small woodland creature majestic bird two natu...,"[small, woodland, creature, majestic, bird, tw..."
3,facing el chapo,two mexican officers must survive final hours ...,"[two, mexican, officers, must, survive, final,..."
4,demon slayer kimetsu no yaiba infinity castle,demon slayer corps drawn infinity castle tanji...,"[demon, slayer, corps, drawn, infinity, castle..."